### ISSUE TITLE
Create Extension for a Mission Summary Field.

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-mission-post-summary#1]
![2021-02-16 15_54_37-USS Test __ Write Mission Post](https://user-images.githubusercontent.com/15860882/108150112-bbeb4f80-7099-11eb-9e09-dec27aed1ac4.png)
![2021-02-16 15_56_08-USS Test __ Edit Mission - Test Mission](https://user-images.githubusercontent.com/15860882/108150113-bc83e600-7099-11eb-92fe-32df0eea7249.png)

1. Add Summary Text Box Here before Content
2. Add Extension options here before Order
- Summary Field Enable checkbox
- Summary Field Label Name (default: Summary)
- Summary Field number of lines for initial size (default 5)
- Include Summary Field in email checkbox

**Comment by pawanmall157** [comment]
done

**Comment by reecesavage** [comment]
![image](https://user-images.githubusercontent.com/15860882/108403149-05e04c80-71e4-11eb-8040-f3ebcb4c994e.png)

- Add a space after the Sumary:
- Can Summary come after timeline?

![image](https://user-images.githubusercontent.com/15860882/108403429-4fc93280-71e4-11eb-8505-fbb791399d57.png)
![image](https://user-images.githubusercontent.com/15860882/108403555-771fff80-71e4-11eb-81da-dfc9f42dcca7.png)

- Add summary to views

![image](https://user-images.githubusercontent.com/15860882/108403724-a6367100-71e4-11eb-8776-4a2c784a7b54.png)

- Change menu name to Mission Posts Summary

![image](https://user-images.githubusercontent.com/15860882/108403819-c108e580-71e4-11eb-8f3f-b222a084dfe8.png)

- Remove Index and check. There isn't a need for an index for this extension.

**Comment by reecesavage** [comment]
![image](https://user-images.githubusercontent.com/15860882/108408056-34612600-71ea-11eb-94cf-83826dcf50be.png)
- Update confirmation message to say Configuration was successfully updated instead of Labeled was successfully updated.
- Change Summary Label Configuration to Summary Configuration
- Change Default Summary Field Size to 5.
- Change Update Labels to Update Configuration

**Comment by pawanmall157** [comment]
done

**Comment by reecesavage** [comment]
confirmed issues fixed
